
-- Create the users table
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    user_name TEXT NOT NULL,
    email TEXT NOT NULL,
    plan TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create the audios table
CREATE TABLE audios (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id TEXT NOT NULL REFERENCES users(id),
    audio_url TEXT NOT NULL,
    audio_name TEXT NOT NULL
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


create table voices (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    voice_id text null default ''::text,
    voice_name text null default ''::text,
    description text null default ''::text,
    type text null default 'free'::text,
    gender text null default ''::text,
    available boolean null,
    premium boolean null,
    constraint voices_pkey primary key (id)
);